### ISSUE TITLE
libusb required

### ISSUE THREAD

**Issue by BrianGilbert** [T3CHNOLOG1C/NX-Bootkit#2]
Mac/Linux
Also need to ensure that user has libusb installed.. for mac this can be done with the following:
```
brew install libusb

**Comment by T3CHNOLOG1C** [comment]
https://github.com/reswitched/fusee-launcher/pull/7 according to ktemkin's comment here, `pyusb` should bring in `libusb` as a dependency, closed.

**Comment by BrianGilbert** [comment]
@T3CHNOLOG1C just sayin.. I installed pyusb as per the instructions I gave and it didn't install a working version of libusb, as soon as I ran `brew install libusb` I was able to send the payload.
